name: Debug with SSH

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Server
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server
          sudo service ssh start

      - name: Set up SSH
        run: |
          # Create the .ssh directory with proper permissions
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Add the public key to the authorized_keys file
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys

          # Allow root login and password authentication
          echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config
          echo "PasswordAuthentication yes" | sudo tee -a /etc/ssh/sshd_config

          # Restart the SSH service
          sudo service ssh restart

      - name: Print SSH Debug Info
        run: |
          echo "SSH Server is running"
          ip addr

      - name: Keep Runner Alive
        run: sleep 1h
