name: Debug with SSH

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Server
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server
          sudo service ssh start

      - name: Set up SSH
        run: |
          # Create the .ssh directory with proper permissions
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Add the public key to the authorized_keys file
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys

          # Allow root login and password authentication
          echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config
          echo "PasswordAuthentication yes" | sudo tee -a /etc/ssh/sshd_config

          # Restart the SSH service
          sudo service ssh restart

      - name: Install Ngrok
        run: |
          # Download the correct ngrok tarball for Linux
          curl -Lo ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
          unzip ngrok.zip
          sudo mv ngrok /usr/local/bin

      - name: Authenticate Ngrok
        run: |
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Start Ngrok Tunnel
        run: |
          nohup ngrok tcp 22 > /dev/null 2>&1 &
          disown

      - name: Print SSH Debug Info
        run: |
          echo "SSH Server is running"
          ip addr

      - name: Keep Runner Alive
        run: sleep 6h
