name: Debug with SSH

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Server
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server
          sudo service ssh start

      - name: Set up SSH
        run: |
          # Create the .ssh directory with proper permissions
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Add the public key to the authorized_keys file
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys

          # Allow root login and password authentication
          echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config
          echo "PasswordAuthentication yes" | sudo tee -a /etc/ssh/sshd_config

          # Restart the SSH service
          sudo service ssh restart

      - name: Download Ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc
          echo "deb https://ngrok-agent.s3.amazonaws.com/deb stable main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt-get update
          sudo apt-get install ngrok

      - name: Authenticate Ngrok
        run: |
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Start Ngrok Tunnel
        run: |
          nohup ngrok tcp 22 &

      - name: Print SSH Debug Info
        run: |
          echo "SSH Server is running"
          ip addr
